# Generated by Django 5.1 on 2025-01-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='business_id_number',
        ),
    ]
