# Generated by Django 5.1 on 2025-02-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-bill_date']},
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(db_index=True, editable=False, max_length=10, unique=True),
        ),
    ]
