# Generated by Django 5.1 on 2025-01-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0004_alter_business_business_id_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_id_number',
            new_name='business_number',
        ),
    ]
