# Generated by Django 5.1 on 2025-01-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0005_rename_business_id_number_business_business_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='business',
        ),
        migrations.AddField(
            model_name='customuser',
            name='test',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
