# Generated by Django 5.1 on 2025-01-19 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0006_remove_customuser_business_customuser_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='test',
            new_name='number',
        ),
    ]
