# Generated by Django 5.1 on 2025-01-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0008_remove_customuser_number_customuser_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_business',
            field=models.BooleanField(default=True),
        ),
    ]
