# Generated by Django 5.1 on 2025-01-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0009_customuser_is_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('owner_alternate_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='vehicle_owner_documents/pan_cards/')),
                ('adhar_card', models.FileField(blank=True, null=True, upload_to='vehicle_owner_documents/adhar_cards/')),
                ('document1', models.FileField(blank=True, null=True, upload_to='vehicle_owner_documents/other_documents/')),
                ('document2', models.FileField(blank=True, null=True, upload_to='vehicle_owner_documents/other_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
