# Generated by Django 5.1 on 2025-01-20 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0010_vehicleowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Developer.business'),
        ),
        migrations.AddField(
            model_name='party',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Developer.business'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Developer.business'),
        ),
        migrations.AddField(
            model_name='vehicleowner',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Developer.business'),
        ),
    ]
