# Generated by Django 5.1 on 2025-01-20 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0011_driver_business_party_business_vehicle_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleowner',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Developer.vehicle'),
        ),
    ]
