# Generated by Django 5.1 on 2025-01-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0012_vehicleowner_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='document3',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='document4',
        ),
    ]
