# Generated by Django 5.1 on 2025-01-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0013_remove_vehicle_document3_remove_vehicle_document4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owner_alternate_mobile_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='owner_mobile_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='owner_name',
        ),
    ]
