# Generated by Django 5.1 on 2025-01-20 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0014_remove_vehicle_owner_alternate_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleowner',
            name='business',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Developer.business'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicleowner',
            name='owner_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicleowner',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Developer.vehicle'),
        ),
    ]
