# Generated by Django 5.1 on 2025-01-20 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0015_alter_vehicleowner_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleowner',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Developer.vehicleowner'),
        ),
    ]
