# Generated by Django 5.1 on 2025-01-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0017_alter_vehicleowner_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleowner',
            name='owner_mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
