# Generated by Django 5.1 on 2025-01-26 08:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0018_alter_vehicleowner_owner_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(editable=False, max_length=10, unique=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Bill Date & Time')),
                ('from_location', models.CharField(max_length=255, verbose_name='From Location')),
                ('to_location', models.CharField(max_length=255, verbose_name='To Location')),
                ('material_type', models.CharField(max_length=255, verbose_name='Type of Material')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rent Amount')),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Advance Amount')),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Pending Amount')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='Developer.driver', verbose_name='Driver')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='Developer.vehicleowner', verbose_name='Vehicle Owner')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='Developer.party', verbose_name='Party Name')),
                ('referece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Developer.vehicleowner', verbose_name='Vehicle Owner')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='Developer.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'ordering': ['-created_at'],
            },
        ),
    ]
