# Generated by Django 5.1 on 2025-01-26 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0019_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='referece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_bills', to='Developer.vehicleowner', verbose_name='Referenced Owner'),
        ),
    ]
