# Generated by Django 5.1 on 2025-01-26 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0020_alter_bill_referece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='Developer.party', verbose_name='Party Name'),
        ),
    ]
