# Generated by Django 5.1 on 2025-01-26 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0021_alter_bill_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Developer.business'),
        ),
    ]
