# Generated by Django 5.1 on 2025-01-26 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0022_bill_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='owner',
        ),
        migrations.AlterField(
            model_name='bill',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='Developer.party', verbose_name='Party Name'),
        ),
    ]
