# Generated by Django 5.1 on 2025-01-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0023_remove_bill_owner_alter_bill_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Advance Amount'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='material_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type of Material'),
        ),
    ]
