# Generated by Django 5.1 on 2025-01-26 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0024_alter_bill_advance_amount_alter_bill_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='vehicle',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='Developer.vehicle', verbose_name='Vehicle'),
            preserve_default=False,
        ),
    ]
