# Generated by Django 5.1 on 2025-01-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0025_alter_bill_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Commission'),
            preserve_default=False,
        ),
    ]
