# Generated by Django 5.1 on 2025-01-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0026_bill_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Commission'),
        ),
    ]
