# Generated by Django 5.1 on 2025-01-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0028_alter_bill_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='advance_amount',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Advance Amount'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Commission'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='pending_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Pending Amount'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='rent_amount',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Rent Amount'),
        ),
    ]
