# Generated by Django 5.1 on 2025-01-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0029_alter_bill_advance_amount_alter_bill_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='alternate_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
