# Generated by Django 5.1.1 on 2025-01-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0031_alter_driver_mobile_alter_party_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='referece',
            new_name='reference',
        ),
    ]
