# Generated by Django 5.1 on 2025-01-29 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0032_rename_referece_bill_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='date_time',
        ),
    ]
