# Generated by Django 5.1 on 2025-01-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0033_remove_bill_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='commission_charge',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Commission Amount'),
        ),
        migrations.AddField(
            model_name='bill',
            name='commission_pending',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Commission Pending'),
        ),
        migrations.AddField(
            model_name='bill',
            name='commission_received',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Commission Received'),
        ),
    ]
